### ISSUE TITLE
The role ec2_node_tools should provide a example playbook

### ISSUE THREAD

**Issue by flyemsafe** [redhat-partner-tech/automated-smart-management#2]
The below playbook works.

**tags**
Make sure you define your own tags, the ones use below may not work for you.

**ec2_region**
Make sure this matches your region.

**ec2_instance_action**
Options are *start* and *stop*

```
---
- hosts: all
  gather_facts: false
  vars:
    ec2_instance_action: "stop"
    ec2_region: us-east-1
    instances:
      tags:
        owner: 'john'
        Workshop: 'Ansible'
  roles:
  - ec2_node_tools
 ```
